//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastEnter
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> UsersID { get; set; }
        public string AttemptToLogin { get; set; }
    
        public virtual User User { get; set; }
    }
}
